{tento soubor je vygenerovan z lang.cz programem lang2inc}
const lang1str='cz';
{$ifdef lang_in_DS}
const hlasky1DS:array[erOk..__] of pchar=(
'',
'',
'Nedostatek pamàti.',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'Nelze otev©°t soubor.',
'Nelze á°st ze souboru.',
'',
'',
'',
'',
'',
'',
'',
'Nekorektn° parametry.',
'Soubor nenalezen.',
'',
'P©°stup odep©en.',
'',
'',
'',
'',
'Neplatn† cesta.',
'Nelze ps†t do souboru.',
'',
'',
'',
'Selh†n° DPMI.',
'',
'',
'',
'Nedostatek konvenán° pamàti.',
'Pot©ebuji DOS verze p©inejmen®°m',
'Neplatny disk',
'Selhalo nastaven° fantom disku',
'Selhal test fantom disku',
'Zabils koáku, ëivotñ màla',
'Nelze vytvo©it soubor.',
'Nelze zav©°t soubor.',
'P©°li® velkò soubor.',
'V readonly m¢du nelze zapisovat na disk.',
'Sluëba Event Wait je obsazena.',
'DialogovÇ okno je vàt®° neë obrazovka, zkus vy®®° rozli®en°.',
'M†lo pamàti na vol†n° shellu "$".',
'Ne£spà®nÇ vol†n° shellu "$".',
'Selhalo naáten° souboru.',
'Selhalo uloëen° souboru.',
'Selhalo vol†n° shellu.',
'Adresa',
'Nejde nastavit zobrazovac° m¢d.',
'Vadnò VESA BIOS. Po©iÉ si slu®nàj®° nebo pouëij VGA rozli®en°.',
'Screen=nil. Je pot©eba nejprve nastavit nàjakò m¢d.',
'Bitmapy maj° rñznÇ modely. Je pot©eba je p©evÇst na spoleánò.',
'Vadnò font.',
'Pokus o nastaven°/konverzi fontu pro tyto £áely p©°li® velkÇho.',
'Chyba v INI souboru na ©†dce:',
'ChybnÇ hexadecim†ln° á°slo v INI souboru na ©†dce:',
'Intern° chyba INI readeru.',
'Ä°slo mimo rozsah $..$ v INI souboru na ©†dce:',
'Promànn† m† bòt á°slo v INI souboru na ©†dce:',
'ReadOnly m¢d, vynech†v†m pr†ci s',
'Alokuje® moc blokñ konvenán° pamàti. Pro autora: zvy® si maxDosBlocks.',
'blokñ konvenán° pamàti neuvolnàno.',
'Tvoje grafick† karta se zbl†znila. Volej doktora d.ment@email.cz!',
'Nenahazuje se ret, intern° chyba.',
'Fuj bios, sluëba load user font zmànila doublescanning.',
'minulò m¢d neuvolnil timer',
'ë†dn† bitmapa na vstupu.',
'p©°li® velk† li®ta.',
'',
'- TEST GRAFICKê KARTY -',
'ûiÉ se instrukcemi na obrazovce.',
'Pokud jsi v oknà, p©epni do fullscreenu!',
'...ENTER - pokraáov†n°...',
'Jestli se text hòbe, stiskni ENTER.',
'V opaánÇm p©°padà ESC.',
'ENTER jestli se text cuk†, jinak ESC',
'Stiskni ENTER.',
'Stiskni ESC.',
'Je-li vidàt jen pñlkruënice, stiskni ESC.',
'Stiskni ENTER, je-li cel†.',
'Stiskni MEZERNãK, je-li cel†.',
'Je-li sloupec textu uprost©ed obrazovky, stiskni ENTER. Je-li vychòlen doprava nebo doleva, stiskni ESC.',
'Pokud se kurzor pohybuje kolmo (v jednom sloupci), stiskni ENTER. Jinak ESC.',
'Pokud se text pohybuje plynule, stiskni ENTER. Jinak ESC.',
'Pokud se text',
'pohybuje plynule,',
'stiskni ENTER.',
'Jinak ESC.',
'',
'Postr†d†m soubor',
'Soubor $ jië existuje.',
'Adres†© $ neexistuje.',
'Nelze otev©°t soubor',
'Nelze á°st ze souboru',
'Nelze naá°st celò soubor',
'Nelze vytvo©it soubor',
'Nelze ps†t do souboru',
'asi je m†lo m°sta na disku.',
'Nelze zav©°t soubor',
'Nelze p©ejmenovat soubor',
'Nelze smazat soubor',
'na',
'Nelze zjistit velikost souboru',
'Nelze zjistit atributy souboru',
'Nelze nastavit atributy souboru',
'Nelze vytvo©it adres†©',
'Nelze vstoupit do adres†©e',
'Nelze smazat adres†©',
'Bàhem akce nastala chyba.',
'Pokraáuj;Pok.vëdy;Skonái;Sko.vëdy',
'õpatn† á°seln† soustava',
'õpatn† cifra na vstupu.',
'Chyba p©°stupu ke streamu',
'Nelze inicializovat stream',
'Äten° za koncem streamu',
'Nelze ps†t do streamu',
'Get neregistrovanÇho typu',
'Put neregistrovanÇho typu',
'MÇdium chr†nàno proti z†pisu.',
'Disk',
'Disky',
'NEPûIPRAVEN',
'Zas nic.',
'PûECPèNO!',
'PûãLIõ MNOHO',
'SOUBOR¶!',
'Äekejte,',
'pros°m',
'ûad°m..',
'Zadej masku.',
'ADRESèû',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'Dàlen° nulou.',
'P©ekroáen° mez° pole nebo typu.',
'P©eteáen° stacku.',
'Nedostatek pamàti.',
'Invalid pointer operation.',
'Floating point overflow.',
'Floating point underflow.',
'Invalid floating point operation.',
'Overlay manager not installed.',
'Overlay file read error.',
'Pouëit° neinicializovanÇho objektu.',
'Vol†n° abstraktn° metody.',
'Stream registration error.',
'Indexov†n° v kolekci mimo rozsah.',
'P©eteáen° kolekce.',
'AritmetickÇ p©eteáen°.',
'General Protection Fault, hehe :).',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'Break, taky ©e®en°.',
'',
'Pouziti: FN [options] [zdroj [cil]]',
'  -i jen vypise informace o fontech zdroj',
'  -f jen vypise informace o formatech',
'  -p prevede font na proporcionalni',
'  -ncislo prevede font na neproporcionalni, cislo je sirka, zadne cislo=detekce',
'  -r umozni prejmenovat font (nazev v headeru, ne nazev souboru)',
'  -first-last rika, ze font obsahuje pouze znaky first az last (napr. -32-255)',
'  -wcislo udava sirku znaku ve FNT v pixelech, implicitne 8',
'  -scislo posune vsechny znaky nahoru (tak lze vytvorit superscript)',
'  -k prevede font z CentralEurope na Kameniky (chces jinou konverzi? call me)',
'  -v zpracuje vsechny fonty obsazene v souboru',
'  -cslovo nejake slovo obsazene v .FON v headeru kazdeho fontu, implicitne (c)',
'   (neznam format .FON, fonty vyhledavam podle tohoto slova)',
'  :lang volba jazyka (:cz nebo :eng)',
'  Pokud je zadan jen zdroj, font se nastavi na obrazovce.',
'  Pokud je zadan i cil, program se pokusi o konverzi.',
'  Zdroj i cil mohou obsahovat * a ? (napr. FN *.fnt *.fn).',
'',
'Formaty (serazene od nejjednodussiho k nejkomplexnejsimu):',
'  FNT - nespakovane bitmapy, sirka 8 pixelu, vyska se autodetekuje',
'  FNP - jako FNT ale pred kazdym znakem je byte sirka(0-8)',
'  RIF - magic "af"; pchar copyright; word vyska(0-24),lastchar (firstchar=32);',
'        tablo[word ofs_od_zacatku_bitmap,sirka(0-16)]; hromada bitmap',
'  FN  - magic "Îm’onÁ "; pchar name; char firstchar,lastchar; short sizeover,',
'        sizeunder; short addspace; byte future; tablo[short relx,rely;',
'        byte sir,vys,shift; word ofs_od_zacatku_souboru]; hromada bitmap',
'  FON - copyright, copyright, copyright, chaos, copyright...',
'',
'Nejak moc parametru.',
'Nezn†mò parametr',
'Chaos 1, sezen mi popis formatu FON.',
'Chaos 2, sezen mi popis formatu FON.',
'Fontu:',
'Pouzit font cislo',
'Font',
'Vyska',
'õ°©ka $ neodpovida parametrum - neni nasobkem $ (znaku*sirka).',
'Prilis velky font.',
'Interni chyba, spatna velikost vygenerovaneho fn.',
'Expand failed.',
'Shrink failed.',
'Z†pis do form†tu .',
'nen° podporov†n.',
'Load $.',
'Rename (zadej libovolne dlouhe jmeno fontu, uklada se do headeru):',
'Proporc.',
'Noprop.',
'Superscript.',
'Show.',
'Save',
'Nezn†mò form†t souboru.',
'',
'Pro takovò form†t nem†m loader.',
'Pro takovò form†t nem†m writer.',
'Nepodporovanò áernob°lò obr†zek!',
'Nepodporovanò typ komprese!',
'Nepodporovan† barevn† hloubka!',
'Postr†d†m paletu!',
'Neoáek†van† paleta!',
'Chyba v datech!',
'P©°li® mnoho Huffmanovòch tabulek!',
'P©°li® mnoho kvantizaán°ch tabulek!',
'P©°li® mnoho barevnòch sloëek!',
'Neprokl†danÇ obr†zky nejsou podporov†ny!',
'Nespr†vnò poáet barevnòch sloëek!',
'Chybn† velikost znaáky DRI!',
'Chybn† velikost hlaviáky souboru!',
'DHL nen° podporov†no!',
'Nalezena nezn†m† znaáka v datech!',
'Barevnò model CMYK nen° podporov†n!',
'Barevnò model YIQ nen° podporov†n!',
'Nezn†mò barevnò model!',
'Aritmetick† komprese nen° podporov†na!',
'Soubory typu HSI JPEG nejsou podporov†ny!',
'Neoáek†van† znaáka konce souboru!',
'Nebyla definov†na ë†dn† Huffmanova dekompresn° tabulka!',
'Nepodporovanò typ prokl†d†n°!',
'Neoáek†van† znaáka v datech!',
'Prokl†d†n° obr†zkñ nen° podporov†no!',
'P©°li® velkò obr†zek!',
'Podporov†ny jsou pouze 256barevnÇ obr†zky!',
'Chyba CRC v hlaviáce souboru!',
'Nalezen neoáek†vanò konec souboru!',
'Obr†zky v progresivn°m m¢du nejsou podporov†ny!',
'Nezn†mò typ komprese!',
'Dekompresn° buffer vàt®° neë 32KB nen° podporov†n!',
'Nezn†mò typ filtru!',
'Chybn† velikost nekomprimovanÇho bloku!',
'Alfa kan†l nen° podporov†n!',
'P©°li® velk† animace pro indirect player.',
'Pamàü staá° jen na $% obr†zku.',
'',
'Nepovolenò n†zev samplu: $',
'',
'Nekorektn° popis pozad°:',
'Syntatick† chyba v popisu pozad°:',
'Nezn†m† barva:',
'',
'Chybnò n†zev projektu, nastuduj roz®°©enou hvàzdiákovou konvenci...',
'Nejd©°v kompiluj - pouzij parametr 1.',
'je v seznamu v°ckr†t!',
'Zadej jmeno $. DM souboru.',
'Nazvi obsah $. DM souboru.',
'Pokud to neni Root, je to AddOn k',
'(ve vyrazu muzes pouzit *,?,[varianta1|varianta2|...])',
'2-3 pismenna zkratka nazvu.',
'',
'(vede na nàj odkaz ze str†nky $).',
'Neza©azen† str†nka: $.',
'Str†nka $ nen° fit! (beru jen str†nky verz° 200..$)',
'Obr†zek $ pouëitò na str†nce $ neexistuje.',
'Vyluáuji z projektu',
'Nehled°m na velikost',
'Prohl°ë°m vazby uvnit© projektu...',
'Nena®el jsem ë†dnÇ str†nky, ze kteròch bych .DM sestavil.',
'Velikost projektu',
'',
'M†lo pamàti pro skript v Parlanu.',
'',
'P©°li® mnoho modulñ na str†nce.',
'',
'P©ekroáen maxim†ln° poáet sloupcñ na str†nce.',
'',
'Zkracuji text.',
'',
'Moc malò buffer pro dmtext.',
'Soubor vytvo©en p©°li® novou verz° Ma®iny.',
'Chyb° str†nka template.',
'Str†nka m† ne£plnò header, moën† k tomu do®lo zmànou template.',
'Mezi ®ablonami vznikla smyáka.',
'',
'P©ekroáen maxim†ln° poáet DM souborñ.',
'P©ekroáen maxim†ln° poáet projektñ.',
'P©°li® mnoho DM souborñ v jednom projektu.',
'Nezkompilov†no',
'mus° bòt root',
'rulez',
'sux',
'none',
'Hled†m DMs v',
'verze',
'Chyb°',
'ale mñëe® si vybrat n†hradn° jazyk.',
'',
'Sorry, p©ekroáen max.poáet vno©en°.',
'Nelze obnovit str†nku (m†lo pamàti nebo intern° chyba).',
'Nastaven° palety (ovl†d†n°: my®, mezern°k, z,x)',
'ESC=v®echno zpàt',
'ENTER=hotovo',
'set',
'Setup',
'help',
'MiniHelp',
'rip',
'Ripper',
'shell',
'DOS shell',
'bye',
'Konec',
'zkou®°m velikost',
'P©etekl ministack.',
'Podtekl ministack.',
'Export do:',
'screenshot',
'obr†zek celÇ str†nky',
'holò text str†nky',
'Vòhe§: hol† str†nka',
'HTML: hol† str†nka',
'HTML: str†nka a obr†zky',
'HTML: celò site, i podstr†nky',
'Ma®ina: hol† str†nka',
'Ma®ina: plnà vybaven† str†nka',
'Ma®ina: celò site, i podstr†nky',
'Str†nka neobsahuje ë†dn† textov† data.',
' Kde hledat hudbu',
'$ nem† vlastn° hudbu.',
'Soubor $ neexistuje.',
'Jakò modul/mp3 chce® pustit?',
'Jakò adres†© chce® pustit?',
'V adres†©i nejsou ë†dnÇ moduly/mp3.',
'Naáteno modulñ: $',
' Pustit modul/mp3 z projektu.',
' Pustit modul/mp3 z disku.',
' Pustit adres†© z disku.',
'Hr†t rad®i podle abecedy.',
'Hr†t rad®i v n†hodnÇm po©ad°.',
'Kdy st©°dat hudbu...',
'Nikdy.',
'Po dohr†n°.',
'Po minutà.',
'Po $ minut†ch.',
' Hr†t p©edchoz°.',
' Hr†t dal®°.',
' Hr†t n†hodnò.',
'Vypnout hudbu.',
'Stopnout $.',
'Zpàt k $.',
'Zpàt k hudbà z $.',
'Spustil jsi Ma®inu bez audiosystÇmu.',
'Toto menu.',
'Setup.',
'Vstup na str†nku.',
'Str†nky podle autorñ.',
'Volba projektu.',
'Volba rozli®en°.',
'Volba jazyka.',
'Export str†nky.',
' Hudba.',
'N†hl† smrt.',
'Hlavn° menu.',
'Editor palety.',
'Mezern°k',
'Link vede na',
'Tento form†t nen° podporov†n.',
'odkazuje na',
'kteròëto soubor nebyl nalezen.',
'Nejde vygenerovat button (®patnÇ parametry nebo m†lo pamàti).',
'Adres†© pro exportovanÇ soubory.',
'Ripping zñstal nedokonáen.',
'Projekt zat°m nem† tituln° str†nku.',
'Vytvo© str†nku "title".',
'Pozor, prohl°ëen° str†nek historickòch',
'verz° 0.xx nen° zcela bezpeánÇ.',
'',
'Zkou®°m',
'Instaluji',
'do',
'Zap°n†m readonly reëim.',
'P©°kazem "SET DM=cesta" mñëe® nastavit kam m† Ma®ina ukl†dat svÇ soubory.',
'Konfiguraán° soubor $ je vytvo©en novàj®° verz° Ma®iny.',
'Pokud chce® mermomoc° pouë°vat tuto star®° verzi, bude® ho muset smazat.',
'Instaluji Ma®inu do',
'Updatuji Masinu v',
'Parametry:       /pouëit°: "dm [parametry]", nap©. "dm 4" prohl°ëen° v textm¢du',
' ?,H     - vyp°®e tento seznam parametrñ',
' S       - safe mode (bezpeánej®° reëim - bez hw scrolu apod)',
' O       - oldies but goldies (áte i .DM soubory verze 0.xx, ale bez z†ruk)',
' R       - readonly mode (vñbec nezapisuje na disk)',
' D,DP,DM,DW,DC,DA,DS - rñznÇ debugovac° m¢dy, lze kombinovat',
'           (debug general,pal,mem,writer,cache,atoms,scripts)',
' I       - instalace (do $ nebo %DM%)',
' E       - editor (tvorba vlastn°ch stranek..)',
' 1       - kompil†tor projektu (vygeneruje seznam souborñ $)',
' 2       - linker projektu (soubory z $ spoj° do .DM)',
' VGA,VESA,NOVGA,NOVESA - vynut° nebo zak†ëe VGA nebo VESA m¢dy',
' OsaRelaceLimit - omez° rozli®en° v ose x nebo y danòm poátem pixelñ',
'           (p©°klady: y=480, xlt800, "x<800", x!=360, "y<100"...)',
' +bitñ   - pouëije pouze m¢dy s tolika bity na pixel (4,8,15,16,24,32)',
' -bitñ   - vynech† m¢dy s tolika bity na pixel       (4=textm¢d)',
' :jazyk  - volba jazyka (:cz nebo :eng)',
' adres†© - tam hled† dal®° .DM soubory',
' soubor  - rovnou otev©e zadanò soubor (.DM nebo str†nka editoru)',
' soubor.swp [MB]-zvet®° pamàü otev©en°m swapfile (implicitnà 16MB) (nestabiln°)',
'Program je jië jednou spu®tàn, m†m rozbàhnout dal®° kopii? [Ano/Ne/Kec†®]',
'AaNnKk',
'Verze p©ilinkovanÇho ini souboru neodpov°d† verzi programu.',
'Jazyk p©ilinkovanÇho ini souboru neodpov°d† jeho n†zvu.',
'',
'Ano;Storno',
'Intern° chyba, ®patnò odhad velikosti str†nky.',
'sloupec',
'bajtñ',
'Str†nka',
'nejde uloëit. Zadej jinò n†zev.',
'Vyber str†nku nebo napi® novÇ jmÇno.',
'Ve sloupci nen° m°sto, udàlej ho ve zdroj†ku nebo jdi do jinÇho sloupce.',
'Vyber obr†zek...',
'Vyber skript...',
'Vyber si font...',
'Kterò font chce® nahradit?',
'Dal®° font ti ned†m, uë m†® na str†nce jinÇ áty©i.',
'Odkaz vede na...',
'M†m tento sloupec slouáit s p©edchoz°m?',
'Vloëen°m obr†zku zru®°® textury na pozad°. Pokraáovat?',
'Definuj pozad° zpñsobem popsanòm v helpu (F1).',
'Velikost str†nky (SIRKAxVYSKA) (®°©kaÚ$).',
'DoporuáenÇ rozli®en° (SIRKAxVYSKA).',
'N†zev str†nky.',
'Autor str†nky.',
'Flags',
'Zab°j°m zlÇ dÇmony...',
'Upozornàn°: Nem†® VESA BIOS.',
'Upozornàn°: Nem†® my®.',
'Check Event Wait...',
'Tvñj operaán° systÇm moment†lnà nepodporuje standardn° sluëbu Event Wait.',
'Mñëu pokraáovat, ale potom neruá°m za vòsledek.',
'Check OS...',
'Upozornàn°: Scrolling je plynulej®° bez Windows.',
'Check memory...',
'Upozornàn°: V°c pamàti by ne®kodilo ;-)',
'Nem†® moc volnÇ pamàti. Mñëu pokraáovat, ale mohou nastat problÇmy.',
'Nastaven° se projev° aë p©i p©°®t°m spu®tàn° editoru.',
'Vyber si jednu z v°ce sad parametrñ skriptu.',
'Skript',
'parametr',
'm† nezn†mò typ',
'nem† zdokumentovanÇ parametry.',
'nepodporuje parametry',
'parametr typu script/link/... mus° bòt posledn°.',
'',
'Kategorie textu',
'Norm†ln° text',
'Odli®enò text (spoluautor, citace, k¢d)',
'Zvòraznànò text, odkazy',
'Silnà zvòraznànò text',
'',
'Bez helpu ani r†nu',
'Novinky',
'!ednews.cz',
'To nejdñleëitàj®° bàhem prvn° minuty',
'!1stmin.cz',
'Co omrknout pak - hlavn° kapitola',
'!editor.cz',
'Kl†vesnice a my®',
'!keys.cz',
'Menu editoru',
'!edmenu.cz',
'Obr†zky a animace',
'!picture.cz',
'Pozad° a textury',
'!texture.cz',
'Zvuk a hudba',
'!sound.cz',
'Projekty',
'!project.cz',
'Atomy, skripty, ParLan',
'!parlan.cz',
'Chyby a hroucen°',
'!bugz.cz',
'Popis form†tu',
'!format.cz',
'',
'Zarovn†n° textu v odstavci',
'implicitn°, jako o odstavec vò®',
'zde zarovn†vat doleva',
'zde zarovn†vat doleva i doprava',
'zde centrovat',
'zde zarovn†vat doprava',
'',
'PomocnÇ funkce',
'Velikost str†nky',
'Template str†nka',
' N†zev str†nky',
' Autor str†nky',
' DoporuáenÇ rozli®en°',
' Obr†zek na pozad°',
' Definice pozad°/barev',
' Seznam fontñ',
' Sampl >˛  (welcome)',
' Sampl  ˛ (wel.again)',
' Sampl  ˛> (yessir)',
' Sampl ˛  (goback)',
' Sampl ˛ (boom)',
' Hudba',
' Flagy',
'Zarovnat odstavec...',
'Vycentrovat sloupec',
'Rozli®en° editoru',
'P©ehodit Y a Z',
'');

{$else}

procedure hlasky1CS;assembler;asm
 dw 1234,1234,1234,1252,1252,1252,1252,1252,1252,1252,1252,1252
 dw 1252,1252,1273,1295,1295,1295,1295,1295,1295,1295,1295,1316
 dw 1333,1333,1349,1349,1349,1349,1349,1364,1386,1386,1386,1386
 dw 1399,1399,1399,1399,1427,1459,1472,1502,1526,1551,1573,1593
 dw 1613,1653,1683,1743,1776,1804,1828,1852,1874,1880,1911,1973
 dw 2024,2085,2096,2159,2188,2238,2264,2310,2355,2387,2457,2491
 dw 2556,2589,2644,2670,2694,2713,2713,2736,2768,2808,2833,2868
 dw 2890,2926,2940,2952,2993,3019,3048,3152,3228,3285,3298,3315
 dw 3329,3339,3339,3355,3377,3398,3418,3439,3463,3484,3505,3532
 dw 3551,3575,3594,3596,3626,3656,3687,3709,3735,3755,3780,3813
 dw 3836,3859,3884,3910,3933,3954,3979,4004,4033,4037,4042,4053
 dw 4061,4070,4082,4090,4098,4104,4111,4123,4130,4130,4130,4130
 dw 4130,4130,4130,4130,4130,4130,4130,4130,4130,4130,4130,4130
 dw 4130,4130,4130,4130,4130,4130,4130,4130,4130,4130,4130,4130
 dw 4130,4130,4130,4130,4130,4130,4130,4130,4130,4130,4130,4130
 dw 4130,4130,4130,4130,4130,4130,4130,4130,4130,4130,4130,4130
 dw 4130,4130,4130,4130,4130,4130,4130,4130,4130,4143,4174,4191
 dw 4209,4235,4259,4284,4317,4347,4371,4406,4431,4457,4490,4508
 dw 4530,4564,4564,4564,4564,4564,4564,4564,4564,4564,4564,4564
 dw 4564,4564,4564,4564,4564,4564,4564,4564,4564,4564,4564,4564
 dw 4564,4564,4564,4564,4564,4564,4564,4564,4564,4564,4564,4564
 dw 4564,4564,4564,4564,4583,4583,4618,4659,4696,4731,4810,4874
 dw 4952,5011,5079,5156,5202,5280,5340,5376,5433,5486,5544,5544
 dw 5602,5668,5726,5804,5873,5950,6020,6092,6152,6152,6172,6188
 dw 6224,6260,6266,6283,6287,6292,6354,6372,6421,6435,6449,6467
 dw 6483,6490,6556,6564,6571,6583,6588,6592,6615,6615,6646,6677
 dw 6709,6736,6766,6783,6802,6817,6851,6886,6916,6956,6989,7016
 dw 7049,7070,7103,7138,7172,7194,7232,7273,7306,7361,7390,7418
 dw 7454,7475,7517,7546,7580,7627,7648,7698,7717,7756,7783,7824
 dw 7854,7854,7880,7880,7904,7937,7951,7951,8018,8055,8076,8102
 dw 8128,8161,8215,8242,8242,8275,8297,8348,8390,8409,8429,8463
 dw 8520,8537,8537,8570,8570,8601,8601,8646,8646,8660,8660,8687
 dw 8729,8752,8814,8844,8844,8881,8916,8958,8972,8985,8990,8993
 dw 8997,9009,9014,9019,9054,9054,9089,9144,9191,9207,9219,9222
 dw 9227,9231,9239,9242,9248,9253,9262,9265,9270,9286,9304,9322
 dw 9332,9342,9362,9379,9398,9416,9439,9468,9488,9517,9548,9586
 dw 9604,9625,9645,9673,9699,9734,9751,9781,9808,9833,9858,9887
 dw 9907,9913,9924,9934,9948,9965,9978,9993,10007,10018,10027,10044
 dw 10080,10090,10096,10113,10134,10149,10165,10178,10193,10201,10212,10224
 dw 10238,10246,10258,10287,10298,10328,10389,10421,10447,10482,10505,10543
 dw 10574,10574,10581,10590,10592,10615,10688,10743,10815,10834,10851,10930
 dw 10970,11031,11106,11157,11217,11278,11315,11361,11421,11474,11536,11604
 dw 11669,11739,11803,11842,11880,11945,12024,12097,12103,12162,12217,12217
 dw 12227,12273,12280,12285,12292,12323,12359,12431,12447,12462,12478,12504
 dw 12554,12570,12609,12663,12709,12750,12785,12799,12813,12818,12839,12867
 dw 12889,12908,12981,13028,13039,13087,13102,13141,13208,13261,13305,13311
 dw 13319,13333,13363,13384,13432,13432,13447,13460,13499,13522,13543,13543
 dw 13561,13568,13578,13614,13624,13657,13667,13683,13691,13703,13713,13730
 dw 13741,13757,13768,13780,13789,13797,13808,13830,13840,13856,13864,13877
 dw 13887,13887,13913,13944,13965,13996,14009,14031,14031,14045,14061,14077
 dw 14091,14105,14126,14144,14166,14179,14199,14221,14240,14259,14276,14282
 dw 14288,14308,14327,14344,14358
 db 'Nedostatek pamàti.'
 db 'Nelze otev©°t soubor.'
 db 'Nelze á°st ze souboru.'
 db 'Nekorektn° parametry.'
 db 'Soubor nenalezen.'
 db 'P©°stup odep©en.'
 db 'Neplatn† cesta.'
 db 'Nelze ps†t do souboru.'
 db 'Selh†n° DPMI.'
 db 'Nedostatek konvenán° pamàti.'
 db 'Pot©ebuji DOS verze p©inejmen®°m'
 db 'Neplatny disk'
 db 'Selhalo nastaven° fantom disku'
 db 'Selhal test fantom disku'
 db 'Zabils koáku, ëivotñ màla'
 db 'Nelze vytvo©it soubor.'
 db 'Nelze zav©°t soubor.'
 db 'P©°li® velkò soubor.'
 db 'V readonly m¢du nelze zapisovat na disk.'
 db 'Sluëba Event Wait je obsazena.'
 db 'DialogovÇ okno je vàt®° neë obrazovka, zkus vy®®° rozli®en°.'
 db 'M†lo pamàti na vol†n° shellu "$".'
 db 'Ne£spà®nÇ vol†n° shellu "$".'
 db 'Selhalo naáten° souboru.'
 db 'Selhalo uloëen° souboru.'
 db 'Selhalo vol†n° shellu.'
 db 'Adresa'
 db 'Nejde nastavit zobrazovac° m¢d.'
 db 'Vadnò VESA BIOS. Po©iÉ si slu®nàj®° nebo pouëij VGA rozli®en°.'
 db 'Screen=nil. Je pot©eba nejprve nastavit nàjakò m¢d.'
 db 'Bitmapy maj° rñznÇ modely. Je pot©eba je p©evÇst na spoleánò.'
 db 'Vadnò font.'
 db 'Pokus o nastaven°/konverzi fontu pro tyto £áely p©°li® velkÇho.'
 db 'Chyba v INI souboru na ©†dce:'
 db 'ChybnÇ hexadecim†ln° á°slo v INI souboru na ©†dce:'
 db 'Intern° chyba INI readeru.'
 db 'Ä°slo mimo rozsah $..$ v INI souboru na ©†dce:'
 db 'Promànn† m† bòt á°slo v INI souboru na ©†dce:'
 db 'ReadOnly m¢d, vynech†v†m pr†ci s'
 db 'Alokuje® moc blokñ konvenán° pamàti. Pro autora: zvy® si maxDosBlocks.'
 db 'blokñ konvenán° pamàti neuvolnàno.'
 db 'Tvoje grafick† karta se zbl†znila. Volej doktora d.ment@email.cz!'
 db 'Nenahazuje se ret, intern° chyba.'
 db 'Fuj bios, sluëba load user font zmànila doublescanning.'
 db 'minulò m¢d neuvolnil timer'
 db 'ë†dn† bitmapa na vstupu.'
 db 'p©°li® velk† li®ta.'
 db '- TEST GRAFICKê KARTY -'
 db 'ûiÉ se instrukcemi na obrazovce.'
 db 'Pokud jsi v oknà, p©epni do fullscreenu!'
 db '...ENTER - pokraáov†n°...'
 db 'Jestli se text hòbe, stiskni ENTER.'
 db 'V opaánÇm p©°padà ESC.'
 db 'ENTER jestli se text cuk†, jinak ESC'
 db 'Stiskni ENTER.'
 db 'Stiskni ESC.'
 db 'Je-li vidàt jen pñlkruënice, stiskni ESC.'
 db 'Stiskni ENTER, je-li cel†.'
 db 'Stiskni MEZERNãK, je-li cel†.'
 db 'Je-li sloupec textu uprost©ed obrazovky, stiskni ENTER. Je-li vychòlen doprava nebo doleva, stiskni ESC.'
 db 'Pokud se kurzor pohybuje kolmo (v jednom sloupci), stiskni ENTER. Jinak ESC.'
 db 'Pokud se text pohybuje plynule, stiskni ENTER. Jinak ESC.'
 db 'Pokud se text'
 db 'pohybuje plynule,'
 db 'stiskni ENTER.'
 db 'Jinak ESC.'
 db 'Postr†d†m soubor'
 db 'Soubor $ jië existuje.'
 db 'Adres†© $ neexistuje.'
 db 'Nelze otev©°t soubor'
 db 'Nelze á°st ze souboru'
 db 'Nelze naá°st celò soubor'
 db 'Nelze vytvo©it soubor'
 db 'Nelze ps†t do souboru'
 db 'asi je m†lo m°sta na disku.'
 db 'Nelze zav©°t soubor'
 db 'Nelze p©ejmenovat soubor'
 db 'Nelze smazat soubor'
 db 'na'
 db 'Nelze zjistit velikost souboru'
 db 'Nelze zjistit atributy souboru'
 db 'Nelze nastavit atributy souboru'
 db 'Nelze vytvo©it adres†©'
 db 'Nelze vstoupit do adres†©e'
 db 'Nelze smazat adres†©'
 db 'Bàhem akce nastala chyba.'
 db 'Pokraáuj;Pok.vëdy;Skonái;Sko.vëdy'
 db 'õpatn† á°seln† soustava'
 db 'õpatn† cifra na vstupu.'
 db 'Chyba p©°stupu ke streamu'
 db 'Nelze inicializovat stream'
 db 'Äten° za koncem streamu'
 db 'Nelze ps†t do streamu'
 db 'Get neregistrovanÇho typu'
 db 'Put neregistrovanÇho typu'
 db 'MÇdium chr†nàno proti z†pisu.'
 db 'Disk'
 db 'Disky'
 db 'NEPûIPRAVEN'
 db 'Zas nic.'
 db 'PûECPèNO!'
 db 'PûãLIõ MNOHO'
 db 'SOUBOR¶!'
 db 'Äekejte,'
 db 'pros°m'
 db 'ûad°m..'
 db 'Zadej masku.'
 db 'ADRESèû'
 db 'Dàlen° nulou.'
 db 'P©ekroáen° mez° pole nebo typu.'
 db 'P©eteáen° stacku.'
 db 'Nedostatek pamàti.'
 db 'Invalid pointer operation.'
 db 'Floating point overflow.'
 db 'Floating point underflow.'
 db 'Invalid floating point operation.'
 db 'Overlay manager not installed.'
 db 'Overlay file read error.'
 db 'Pouëit° neinicializovanÇho objektu.'
 db 'Vol†n° abstraktn° metody.'
 db 'Stream registration error.'
 db 'Indexov†n° v kolekci mimo rozsah.'
 db 'P©eteáen° kolekce.'
 db 'AritmetickÇ p©eteáen°.'
 db 'General Protection Fault, hehe :).'
 db 'Break, taky ©e®en°.'
 db 'Pouziti: FN [options] [zdroj [cil]]'
 db '  -i jen vypise informace o fontech zdroj'
 db '  -f jen vypise informace o formatech'
 db '  -p prevede font na proporcionalni'
 db '  -ncislo prevede font na neproporcionalni, cislo je sirka, zadne cislo=detekce'
 db '  -r umozni prejmenovat font (nazev v headeru, ne nazev souboru)'
 db '  -first-last rika, ze font obsahuje pouze znaky first az last (napr. -32-255)'
 db '  -wcislo udava sirku znaku ve FNT v pixelech, implicitne 8'
 db '  -scislo posune vsechny znaky nahoru (tak lze vytvorit superscript)'
 db '  -k prevede font z CentralEurope na Kameniky (chces jinou konverzi? call me)'
 db '  -v zpracuje vsechny fonty obsazene v souboru'
 db '  -cslovo nejake slovo obsazene v .FON v headeru kazdeho fontu, implicitne (c)'
 db '   (neznam format .FON, fonty vyhledavam podle tohoto slova)'
 db '  :lang volba jazyka (:cz nebo :eng)'
 db '  Pokud je zadan jen zdroj, font se nastavi na obrazovce.'
 db '  Pokud je zadan i cil, program se pokusi o konverzi.'
 db '  Zdroj i cil mohou obsahovat * a ? (napr. FN *.fnt *.fn).'
 db 'Formaty (serazene od nejjednodussiho k nejkomplexnejsimu):'
 db '  FNT - nespakovane bitmapy, sirka 8 pixelu, vyska se autodetekuje'
 db '  FNP - jako FNT ale pred kazdym znakem je byte sirka(0-8)'
 db '  RIF - magic "af"; pchar copyright; word vyska(0-24),lastchar (firstchar=32);'
 db '        tablo[word ofs_od_zacatku_bitmap,sirka(0-16)]; hromada bitmap'
 db '  FN  - magic "Îm’onÁ "; pchar name; char firstchar,lastchar; short sizeover,'
 db '        sizeunder; short addspace; byte future; tablo[short relx,rely;'
 db '        byte sir,vys,shift; word ofs_od_zacatku_souboru]; hromada bitmap'
 db '  FON - copyright, copyright, copyright, chaos, copyright...'
 db 'Nejak moc parametru.'
 db 'Nezn†mò parametr'
 db 'Chaos 1, sezen mi popis formatu FON.'
 db 'Chaos 2, sezen mi popis formatu FON.'
 db 'Fontu:'
 db 'Pouzit font cislo'
 db 'Font'
 db 'Vyska'
 db 'õ°©ka $ neodpovida parametrum - neni nasobkem $ (znaku*sirka).'
 db 'Prilis velky font.'
 db 'Interni chyba, spatna velikost vygenerovaneho fn.'
 db 'Expand failed.'
 db 'Shrink failed.'
 db 'Z†pis do form†tu .'
 db 'nen° podporov†n.'
 db 'Load $.'
 db 'Rename (zadej libovolne dlouhe jmeno fontu, uklada se do headeru):'
 db 'Proporc.'
 db 'Noprop.'
 db 'Superscript.'
 db 'Show.'
 db 'Save'
 db 'Nezn†mò form†t souboru.'
 db 'Pro takovò form†t nem†m loader.'
 db 'Pro takovò form†t nem†m writer.'
 db 'Nepodporovanò áernob°lò obr†zek!'
 db 'Nepodporovanò typ komprese!'
 db 'Nepodporovan† barevn† hloubka!'
 db 'Postr†d†m paletu!'
 db 'Neoáek†van† paleta!'
 db 'Chyba v datech!'
 db 'P©°li® mnoho Huffmanovòch tabulek!'
 db 'P©°li® mnoho kvantizaán°ch tabulek!'
 db 'P©°li® mnoho barevnòch sloëek!'
 db 'Neprokl†danÇ obr†zky nejsou podporov†ny!'
 db 'Nespr†vnò poáet barevnòch sloëek!'
 db 'Chybn† velikost znaáky DRI!'
 db 'Chybn† velikost hlaviáky souboru!'
 db 'DHL nen° podporov†no!'
 db 'Nalezena nezn†m† znaáka v datech!'
 db 'Barevnò model CMYK nen° podporov†n!'
 db 'Barevnò model YIQ nen° podporov†n!'
 db 'Nezn†mò barevnò model!'
 db 'Aritmetick† komprese nen° podporov†na!'
 db 'Soubory typu HSI JPEG nejsou podporov†ny!'
 db 'Neoáek†van† znaáka konce souboru!'
 db 'Nebyla definov†na ë†dn† Huffmanova dekompresn° tabulka!'
 db 'Nepodporovanò typ prokl†d†n°!'
 db 'Neoáek†van† znaáka v datech!'
 db 'Prokl†d†n° obr†zkñ nen° podporov†no!'
 db 'P©°li® velkò obr†zek!'
 db 'Podporov†ny jsou pouze 256barevnÇ obr†zky!'
 db 'Chyba CRC v hlaviáce souboru!'
 db 'Nalezen neoáek†vanò konec souboru!'
 db 'Obr†zky v progresivn°m m¢du nejsou podporov†ny!'
 db 'Nezn†mò typ komprese!'
 db 'Dekompresn° buffer vàt®° neë 32KB nen° podporov†n!'
 db 'Nezn†mò typ filtru!'
 db 'Chybn† velikost nekomprimovanÇho bloku!'
 db 'Alfa kan†l nen° podporov†n!'
 db 'P©°li® velk† animace pro indirect player.'
 db 'Pamàü staá° jen na $% obr†zku.'
 db 'Nepovolenò n†zev samplu: $'
 db 'Nekorektn° popis pozad°:'
 db 'Syntatick† chyba v popisu pozad°:'
 db 'Nezn†m† barva:'
 db 'Chybnò n†zev projektu, nastuduj roz®°©enou hvàzdiákovou konvenci...'
 db 'Nejd©°v kompiluj - pouzij parametr 1.'
 db 'je v seznamu v°ckr†t!'
 db 'Zadej jmeno $. DM souboru.'
 db 'Nazvi obsah $. DM souboru.'
 db 'Pokud to neni Root, je to AddOn k'
 db '(ve vyrazu muzes pouzit *,?,[varianta1|varianta2|...])'
 db '2-3 pismenna zkratka nazvu.'
 db '(vede na nàj odkaz ze str†nky $).'
 db 'Neza©azen† str†nka: $.'
 db 'Str†nka $ nen° fit! (beru jen str†nky verz° 200..$)'
 db 'Obr†zek $ pouëitò na str†nce $ neexistuje.'
 db 'Vyluáuji z projektu'
 db 'Nehled°m na velikost'
 db 'Prohl°ë°m vazby uvnit© projektu...'
 db 'Nena®el jsem ë†dnÇ str†nky, ze kteròch bych .DM sestavil.'
 db 'Velikost projektu'
 db 'M†lo pamàti pro skript v Parlanu.'
 db 'P©°li® mnoho modulñ na str†nce.'
 db 'P©ekroáen maxim†ln° poáet sloupcñ na str†nce.'
 db 'Zkracuji text.'
 db 'Moc malò buffer pro dmtext.'
 db 'Soubor vytvo©en p©°li® novou verz° Ma®iny.'
 db 'Chyb° str†nka template.'
 db 'Str†nka m† ne£plnò header, moën† k tomu do®lo zmànou template.'
 db 'Mezi ®ablonami vznikla smyáka.'
 db 'P©ekroáen maxim†ln° poáet DM souborñ.'
 db 'P©ekroáen maxim†ln° poáet projektñ.'
 db 'P©°li® mnoho DM souborñ v jednom projektu.'
 db 'Nezkompilov†no'
 db 'mus° bòt root'
 db 'rulez'
 db 'sux'
 db 'none'
 db 'Hled†m DMs v'
 db 'verze'
 db 'Chyb°'
 db 'ale mñëe® si vybrat n†hradn° jazyk.'
 db 'Sorry, p©ekroáen max.poáet vno©en°.'
 db 'Nelze obnovit str†nku (m†lo pamàti nebo intern° chyba).'
 db 'Nastaven° palety (ovl†d†n°: my®, mezern°k, z,x)'
 db 'ESC=v®echno zpàt'
 db 'ENTER=hotovo'
 db 'set'
 db 'Setup'
 db 'help'
 db 'MiniHelp'
 db 'rip'
 db 'Ripper'
 db 'shell'
 db 'DOS shell'
 db 'bye'
 db 'Konec'
 db 'zkou®°m velikost'
 db 'P©etekl ministack.'
 db 'Podtekl ministack.'
 db 'Export do:'
 db 'screenshot'
 db 'obr†zek celÇ str†nky'
 db 'holò text str†nky'
 db 'Vòhe§: hol† str†nka'
 db 'HTML: hol† str†nka'
 db 'HTML: str†nka a obr†zky'
 db 'HTML: celò site, i podstr†nky'
 db 'Ma®ina: hol† str†nka'
 db 'Ma®ina: plnà vybaven† str†nka'
 db 'Ma®ina: celò site, i podstr†nky'
 db 'Str†nka neobsahuje ë†dn† textov† data.'
 db ' Kde hledat hudbu'
 db '$ nem† vlastn° hudbu.'
 db 'Soubor $ neexistuje.'
 db 'Jakò modul/mp3 chce® pustit?'
 db 'Jakò adres†© chce® pustit?'
 db 'V adres†©i nejsou ë†dnÇ moduly/mp3.'
 db 'Naáteno modulñ: $'
 db ' Pustit modul/mp3 z projektu.'
 db ' Pustit modul/mp3 z disku.'
 db ' Pustit adres†© z disku.'
 db 'Hr†t rad®i podle abecedy.'
 db 'Hr†t rad®i v n†hodnÇm po©ad°.'
 db 'Kdy st©°dat hudbu...'
 db 'Nikdy.'
 db 'Po dohr†n°.'
 db 'Po minutà.'
 db 'Po $ minut†ch.'
 db ' Hr†t p©edchoz°.'
 db ' Hr†t dal®°.'
 db ' Hr†t n†hodnò.'
 db 'Vypnout hudbu.'
 db 'Stopnout $.'
 db 'Zpàt k $.'
 db 'Zpàt k hudbà z $.'
 db 'Spustil jsi Ma®inu bez audiosystÇmu.'
 db 'Toto menu.'
 db 'Setup.'
 db 'Vstup na str†nku.'
 db 'Str†nky podle autorñ.'
 db 'Volba projektu.'
 db 'Volba rozli®en°.'
 db 'Volba jazyka.'
 db 'Export str†nky.'
 db ' Hudba.'
 db 'N†hl† smrt.'
 db 'Hlavn° menu.'
 db 'Editor palety.'
 db 'Mezern°k'
 db 'Link vede na'
 db 'Tento form†t nen° podporov†n.'
 db 'odkazuje na'
 db 'kteròëto soubor nebyl nalezen.'
 db 'Nejde vygenerovat button (®patnÇ parametry nebo m†lo pamàti).'
 db 'Adres†© pro exportovanÇ soubory.'
 db 'Ripping zñstal nedokonáen.'
 db 'Projekt zat°m nem† tituln° str†nku.'
 db 'Vytvo© str†nku "title".'
 db 'Pozor, prohl°ëen° str†nek historickòch'
 db 'verz° 0.xx nen° zcela bezpeánÇ.'
 db 'Zkou®°m'
 db 'Instaluji'
 db 'do'
 db 'Zap°n†m readonly reëim.'
 db 'P©°kazem "SET DM=cesta" mñëe® nastavit kam m† Ma®ina ukl†dat svÇ soubory.'
 db 'Konfiguraán° soubor $ je vytvo©en novàj®° verz° Ma®iny.'
 db 'Pokud chce® mermomoc° pouë°vat tuto star®° verzi, bude® ho muset smazat.'
 db 'Instaluji Ma®inu do'
 db 'Updatuji Masinu v'
 db 'Parametry:       /pouëit°: "dm [parametry]", nap©. "dm 4" prohl°ëen° v textm¢du'
 db ' ?,H     - vyp°®e tento seznam parametrñ'
 db ' S       - safe mode (bezpeánej®° reëim - bez hw scrolu apod)'
 db ' O       - oldies but goldies (áte i .DM soubory verze 0.xx, ale bez z†ruk)'
 db ' R       - readonly mode (vñbec nezapisuje na disk)'
 db ' D,DP,DM,DW,DC,DA,DS - rñznÇ debugovac° m¢dy, lze kombinovat'
 db '           (debug general,pal,mem,writer,cache,atoms,scripts)'
 db ' I       - instalace (do $ nebo %DM%)'
 db ' E       - editor (tvorba vlastn°ch stranek..)'
 db ' 1       - kompil†tor projektu (vygeneruje seznam souborñ $)'
 db ' 2       - linker projektu (soubory z $ spoj° do .DM)'
 db ' VGA,VESA,NOVGA,NOVESA - vynut° nebo zak†ëe VGA nebo VESA m¢dy'
 db ' OsaRelaceLimit - omez° rozli®en° v ose x nebo y danòm poátem pixelñ'
 db '           (p©°klady: y=480, xlt800, "x<800", x!=360, "y<100"...)'
 db ' +bitñ   - pouëije pouze m¢dy s tolika bity na pixel (4,8,15,16,24,32)'
 db ' -bitñ   - vynech† m¢dy s tolika bity na pixel       (4=textm¢d)'
 db ' :jazyk  - volba jazyka (:cz nebo :eng)'
 db ' adres†© - tam hled† dal®° .DM soubory'
 db ' soubor  - rovnou otev©e zadanò soubor (.DM nebo str†nka editoru)'
 db ' soubor.swp [MB]-zvet®° pamàü otev©en°m swapfile (implicitnà 16MB) (nestabiln°)'
 db 'Program je jië jednou spu®tàn, m†m rozbàhnout dal®° kopii? [Ano/Ne/Kec†®]'
 db 'AaNnKk'
 db 'Verze p©ilinkovanÇho ini souboru neodpov°d† verzi programu.'
 db 'Jazyk p©ilinkovanÇho ini souboru neodpov°d† jeho n†zvu.'
 db 'Ano;Storno'
 db 'Intern° chyba, ®patnò odhad velikosti str†nky.'
 db 'sloupec'
 db 'bajtñ'
 db 'Str†nka'
 db 'nejde uloëit. Zadej jinò n†zev.'
 db 'Vyber str†nku nebo napi® novÇ jmÇno.'
 db 'Ve sloupci nen° m°sto, udàlej ho ve zdroj†ku nebo jdi do jinÇho sloupce.'
 db 'Vyber obr†zek...'
 db 'Vyber skript...'
 db 'Vyber si font...'
 db 'Kterò font chce® nahradit?'
 db 'Dal®° font ti ned†m, uë m†® na str†nce jinÇ áty©i.'
 db 'Odkaz vede na...'
 db 'M†m tento sloupec slouáit s p©edchoz°m?'
 db 'Vloëen°m obr†zku zru®°® textury na pozad°. Pokraáovat?'
 db 'Definuj pozad° zpñsobem popsanòm v helpu (F1).'
 db 'Velikost str†nky (SIRKAxVYSKA) (®°©kaÚ$).'
 db 'DoporuáenÇ rozli®en° (SIRKAxVYSKA).'
 db 'N†zev str†nky.'
 db 'Autor str†nky.'
 db 'Flags'
 db 'Zab°j°m zlÇ dÇmony...'
 db 'Upozornàn°: Nem†® VESA BIOS.'
 db 'Upozornàn°: Nem†® my®.'
 db 'Check Event Wait...'
 db 'Tvñj operaán° systÇm moment†lnà nepodporuje standardn° sluëbu Event Wait.'
 db 'Mñëu pokraáovat, ale potom neruá°m za vòsledek.'
 db 'Check OS...'
 db 'Upozornàn°: Scrolling je plynulej®° bez Windows.'
 db 'Check memory...'
 db 'Upozornàn°: V°c pamàti by ne®kodilo ;-)'
 db 'Nem†® moc volnÇ pamàti. Mñëu pokraáovat, ale mohou nastat problÇmy.'
 db 'Nastaven° se projev° aë p©i p©°®t°m spu®tàn° editoru.'
 db 'Vyber si jednu z v°ce sad parametrñ skriptu.'
 db 'Skript'
 db 'parametr'
 db 'm† nezn†mò typ'
 db 'nem† zdokumentovanÇ parametry.'
 db 'nepodporuje parametry'
 db 'parametr typu script/link/... mus° bòt posledn°.'
 db 'Kategorie textu'
 db 'Norm†ln° text'
 db 'Odli®enò text (spoluautor, citace, k¢d)'
 db 'Zvòraznànò text, odkazy'
 db 'Silnà zvòraznànò text'
 db 'Bez helpu ani r†nu'
 db 'Novinky'
 db '!ednews.cz'
 db 'To nejdñleëitàj®° bàhem prvn° minuty'
 db '!1stmin.cz'
 db 'Co omrknout pak - hlavn° kapitola'
 db '!editor.cz'
 db 'Kl†vesnice a my®'
 db '!keys.cz'
 db 'Menu editoru'
 db '!edmenu.cz'
 db 'Obr†zky a animace'
 db '!picture.cz'
 db 'Pozad° a textury'
 db '!texture.cz'
 db 'Zvuk a hudba'
 db '!sound.cz'
 db 'Projekty'
 db '!project.cz'
 db 'Atomy, skripty, ParLan'
 db '!parlan.cz'
 db 'Chyby a hroucen°'
 db '!bugz.cz'
 db 'Popis form†tu'
 db '!format.cz'
 db 'Zarovn†n° textu v odstavci'
 db 'implicitn°, jako o odstavec vò®'
 db 'zde zarovn†vat doleva'
 db 'zde zarovn†vat doleva i doprava'
 db 'zde centrovat'
 db 'zde zarovn†vat doprava'
 db 'PomocnÇ funkce'
 db 'Velikost str†nky'
 db 'Template str†nka'
 db ' N†zev str†nky'
 db ' Autor str†nky'
 db ' DoporuáenÇ rozli®en°'
 db ' Obr†zek na pozad°'
 db ' Definice pozad°/barev'
 db ' Seznam fontñ'
 db ' Sampl >˛  (welcome)'
 db ' Sampl  ˛ (wel.again)'
 db ' Sampl  ˛> (yessir)'
 db ' Sampl ˛  (goback)'
 db ' Sampl ˛ (boom)'
 db ' Hudba'
 db ' Flagy'
 db 'Zarovnat odstavec...'
 db 'Vycentrovat sloupec'
 db 'Rozli®en° editoru'
 db 'P©ehodit Y a Z'
end;

{$endif}
