{tento soubor je vygenerovan z lang.cz programem lang2inc}
const lang1str='cz';
{$ifdef lang_in_DS}
const hlasky1DS:array[erOk..__] of pchar=(
'',
'',
'Nedostatek pamàti.',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'Nelze otev©°t soubor.',
'Nelze á°st ze souboru.',
'',
'',
'',
'',
'',
'',
'',
'Nekorektn° parametry.',
'Soubor nenalezen.',
'',
'P©°stup odep©en.',
'',
'',
'',
'',
'Neplatn† cesta.',
'Nelze ps†t do souboru.',
'',
'',
'',
'Selh†n° DPMI.',
'',
'',
'',
'Nedostatek konvenán° pamàti.',
'Pot©ebuji DOS verze p©inejmen®°m',
'Neplatny disk',
'Selhalo nastaven° fantom disku',
'Selhal test fantom disku',
'Zabils koáku, ëivotñ màla',
'Nelze vytvo©it soubor.',
'Nelze zav©°t soubor.',
'P©°li® velkò soubor.',
'V readonly m¢du nelze zapisovat na disk.',
'Sluëba Event Wait je obsazena.',
'DialogovÇ okno je vàt®° neë obrazovka, zkus vy®®° rozli®en°.',
'M†lo pamàti na vol†n° shellu "$".',
'Ne£spà®nÇ vol†n° shellu "$".',
'Selhalo naáten° souboru.',
'Selhalo uloëen° souboru.',
'Selhalo vol†n° shellu.',
'Adresa',
'Nejde nastavit zobrazovac° m¢d.',
'Vadnò VESA BIOS. Po©iÉ si slu®nàj®° nebo pouëij VGA rozli®en°.',
'Screen=nil. Je pot©eba nejprve nastavit nàjakò m¢d.',
'Bitmapy maj° rñznÇ modely. Je pot©eba je p©evÇst na spoleánò.',
'Vadnò font.',
'Pokus o nastaven°/konverzi fontu pro tyto £áely p©°li® velkÇho.',
'Chyba v INI souboru na ©†dce:',
'ChybnÇ hexadecim†ln° á°slo v INI souboru na ©†dce:',
'Intern° chyba INI readeru.',
'Ä°slo mimo rozsah $..$ v INI souboru na ©†dce:',
'Promànn† m† bòt á°slo v INI souboru na ©†dce:',
'ReadOnly m¢d, vynech†v†m pr†ci s',
'Alokuje® moc blokñ konvenán° pamàti. Pro autora: zvy® si maxDosBlocks.',
'blokñ konvenán° pamàti neuvolnàno.',
'Tvoje grafick† karta se zbl†znila. Volej doktora d.ment@email.cz!',
'Nenahazuje se ret, intern° chyba.',
'Fuj bios, sluëba load user font zmànila doublescanning.',
'minulò m¢d neuvolnil timer',
'ë†dn† bitmapa na vstupu.',
'p©°li® velk† li®ta.',
'',
'- TEST GRAFICKê KARTY -',
'ûiÉ se instrukcemi na obrazovce.',
'Pokud jsi v oknà, p©epni do fullscreenu!',
'...ENTER - pokraáov†n°...',
'Jestli se text hòbe, stiskni ENTER.',
'V opaánÇm p©°padà ESC.',
'ENTER jestli se text cuk†, jinak ESC',
'Stiskni ENTER.',
'Stiskni ESC.',
'Je-li vidàt jen pñlkruënice, stiskni ESC.',
'Stiskni ENTER, je-li cel†.',
'Stiskni MEZERNãK, je-li cel†.',
'Je-li sloupec textu uprost©ed obrazovky, stiskni ENTER. Je-li vychòlen doprava nebo doleva, stiskni ESC.',
'Pokud se kurzor pohybuje kolmo (v jednom sloupci), stiskni ENTER. Jinak ESC.',
'Pokud se text pohybuje plynule, stiskni ENTER. Jinak ESC.',
'Pokud se text',
'pohybuje plynule,',
'stiskni ENTER.',
'Jinak ESC.',
'',
'Postr†d†m soubor',
'Soubor $ jië existuje.',
'Adres†© $ neexistuje.',
'Nelze otev©°t soubor',
'Nelze á°st ze souboru',
'Nelze naá°st celò soubor',
'Nelze vytvo©it soubor',
'Nelze ps†t do souboru',
'asi je m†lo m°sta na disku.',
'Nelze zav©°t soubor',
'Nelze p©ejmenovat soubor',
'Nelze smazat soubor',
'na',
'Nelze zjistit velikost souboru',
'Nelze zjistit atributy souboru',
'Nelze nastavit atributy souboru',
'Nelze vytvo©it adres†©',
'Nelze vstoupit do adres†©e',
'Nelze smazat adres†©',
'Bàhem akce nastala chyba.',
'Pokraáuj;Pok.vëdy;Skonái;Sko.vëdy',
'õpatn† á°seln† soustava',
'õpatn† cifra na vstupu.',
'Chyba p©°stupu ke streamu',
'Nelze inicializovat stream',
'Äten° za koncem streamu',
'Nelze ps†t do streamu',
'Get neregistrovanÇho typu',
'Put neregistrovanÇho typu',
'MÇdium chr†nàno proti z†pisu.',
'Disk',
'Disky',
'NEPûIPRAVEN',
'Zas nic.',
'PûECPèNO!',
'PûãLIõ MNOHO',
'SOUBOR¶!',
'Äekejte,',
'pros°m',
'ûad°m..',
'Zadej masku.',
'ADRESèû',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'Dàlen° nulou.',
'P©ekroáen° mez° pole nebo typu.',
'P©eteáen° stacku.',
'Nedostatek pamàti.',
'Invalid pointer operation.',
'Floating point overflow.',
'Floating point underflow.',
'Invalid floating point operation.',
'Overlay manager not installed.',
'Overlay file read error.',
'Pouëit° neinicializovanÇho objektu.',
'Vol†n° abstraktn° metody.',
'Stream registration error.',
'Indexov†n° v kolekci mimo rozsah.',
'P©eteáen° kolekce.',
'AritmetickÇ p©eteáen°.',
'General Protection Fault, hehe :).',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'Break, taky ©e®en°.',
'',
'Pouziti: FN [options] [zdroj [cil]]',
'  -i jen vypise informace o fontech zdroj',
'  -f jen vypise informace o formatech',
'  -p prevede font na proporcionalni',
'  -ncislo prevede font na neproporcionalni, cislo je sirka, zadne cislo=detekce',
'  -r umozni prejmenovat font (nazev v headeru, ne nazev souboru)',
'  -first-last rika, ze font obsahuje pouze znaky first az last (napr. -32-255)',
'  -wcislo udava sirku znaku ve FNT v pixelech, implicitne 8',
'  -scislo posune vsechny znaky nahoru (tak lze vytvorit superscript)',
'  -k prevede font z CentralEurope na Kameniky (chces jinou konverzi? call me)',
'  -v zpracuje vsechny fonty obsazene v souboru',
'  -cslovo nejake slovo obsazene v .FON v headeru kazdeho fontu, implicitne (c)',
'   (neznam format .FON, fonty vyhledavam podle tohoto slova)',
'  :lang volba jazyka (:cz nebo :eng)',
'  Pokud je zadan jen zdroj, font se nastavi na obrazovce.',
'  Pokud je zadan i cil, program se pokusi o konverzi.',
'  Zdroj i cil mohou obsahovat * a ? (napr. FN *.fnt *.fn).',
'',
'Formaty (serazene od nejjednodussiho k nejkomplexnejsimu):',
'  FNT - nespakovane bitmapy, sirka 8 pixelu, vyska se autodetekuje',
'  FNP - jako FNT ale pred kazdym znakem je byte sirka(0-8)',
'  RIF - magic "af"; pchar copyright; word vyska(0-24),lastchar (firstchar=32);',
'        tablo[word ofs_od_zacatku_bitmap,sirka(0-16)]; hromada bitmap',
'  FN  - magic "Îm’onÁ "; pchar name; char firstchar,lastchar; short sizeover,',
'        sizeunder; short addspace; byte future; tablo[short relx,rely;',
'        byte sir,vys,shift; word ofs_od_zacatku_souboru]; hromada bitmap',
'  FON - copyright, copyright, copyright, chaos, copyright...',
'',
'Nejak moc parametru.',
'Nezn†mò parametr',
'Chaos 1, sezen mi popis formatu FON.',
'Chaos 2, sezen mi popis formatu FON.',
'Fontu:',
'Pouzit font cislo',
'Font',
'Vyska',
'õ°©ka $ neodpovida parametrum - neni nasobkem $ (znaku*sirka).',
'Prilis velky font.',
'Interni chyba, spatna velikost vygenerovaneho fn.',
'Expand failed.',
'Shrink failed.',
'Z†pis do form†tu .',
'nen° podporov†n.',
'Load $.',
'Rename (zadej libovolne dlouhe jmeno fontu, uklada se do headeru):',
'Proporc.',
'Noprop.',
'Superscript.',
'Show.',
'Save',
'Nezn†mò form†t souboru.',
'',
'Pro takovò form†t nem†m loader.',
'Pro takovò form†t nem†m writer.',
'Nepodporovanò áernob°lò obr†zek!',
'Nepodporovanò typ komprese!',
'Nepodporovan† barevn† hloubka!',
'Postr†d†m paletu!',
'Neoáek†van† paleta!',
'Chyba v datech!',
'P©°li® mnoho Huffmanovòch tabulek!',
'P©°li® mnoho kvantizaán°ch tabulek!',
'P©°li® mnoho barevnòch sloëek!',
'Neprokl†danÇ obr†zky nejsou podporov†ny!',
'Nespr†vnò poáet barevnòch sloëek!',
'Chybn† velikost znaáky DRI!',
'Chybn† velikost hlaviáky souboru!',
'DHL nen° podporov†no!',
'Nalezena nezn†m† znaáka v datech!',
'Barevnò model CMYK nen° podporov†n!',
'Barevnò model YIQ nen° podporov†n!',
'Nezn†mò barevnò model!',
'Aritmetick† komprese nen° podporov†na!',
'Soubory typu HSI JPEG nejsou podporov†ny!',
'Neoáek†van† znaáka konce souboru!',
'Nebyla definov†na ë†dn† Huffmanova dekompresn° tabulka!',
'Nepodporovanò typ prokl†d†n°!',
'Neoáek†van† znaáka v datech!',
'Prokl†d†n° obr†zkñ nen° podporov†no!',
'P©°li® velkò obr†zek!',
'Podporov†ny jsou pouze 256barevnÇ obr†zky!',
'Chyba CRC v hlaviáce souboru!',
'Nalezen neoáek†vanò konec souboru!',
'Obr†zky v progresivn°m m¢du nejsou podporov†ny!',
'Nezn†mò typ komprese!',
'Dekompresn° buffer vàt®° neë 32KB nen° podporov†n!',
'Nezn†mò typ filtru!',
'Chybn† velikost nekomprimovanÇho bloku!',
'Alfa kan†l nen° podporov†n!',
'P©°li® velk† animace pro indirect player.',
'Pamàü staá° jen na $% obr†zku.',
'');

{$else}

procedure hlasky1CS;assembler;asm
 dw 698,698,698,716,716,716,716,716,716,716,716,716
 dw 716,716,737,759,759,759,759,759,759,759,759,780
 dw 797,797,813,813,813,813,813,828,850,850,850,850
 dw 863,863,863,863,891,923,936,966,990,1015,1037,1057
 dw 1077,1117,1147,1207,1240,1268,1292,1316,1338,1344,1375,1437
 dw 1488,1549,1560,1623,1652,1702,1728,1774,1819,1851,1921,1955
 dw 2020,2053,2108,2134,2158,2177,2177,2200,2232,2272,2297,2332
 dw 2354,2390,2404,2416,2457,2483,2512,2616,2692,2749,2762,2779
 dw 2793,2803,2803,2819,2841,2862,2882,2903,2927,2948,2969,2996
 dw 3015,3039,3058,3060,3090,3120,3151,3173,3199,3219,3244,3277
 dw 3300,3323,3348,3374,3397,3418,3443,3468,3497,3501,3506,3517
 dw 3525,3534,3546,3554,3562,3568,3575,3587,3594,3594,3594,3594
 dw 3594,3594,3594,3594,3594,3594,3594,3594,3594,3594,3594,3594
 dw 3594,3594,3594,3594,3594,3594,3594,3594,3594,3594,3594,3594
 dw 3594,3594,3594,3594,3594,3594,3594,3594,3594,3594,3594,3594
 dw 3594,3594,3594,3594,3594,3594,3594,3594,3594,3594,3594,3594
 dw 3594,3594,3594,3594,3594,3594,3594,3594,3594,3607,3638,3655
 dw 3673,3699,3723,3748,3781,3811,3835,3870,3895,3921,3954,3972
 dw 3994,4028,4028,4028,4028,4028,4028,4028,4028,4028,4028,4028
 dw 4028,4028,4028,4028,4028,4028,4028,4028,4028,4028,4028,4028
 dw 4028,4028,4028,4028,4028,4028,4028,4028,4028,4028,4028,4028
 dw 4028,4028,4028,4028,4047,4047,4082,4123,4160,4195,4274,4338
 dw 4416,4475,4543,4620,4666,4744,4804,4840,4897,4950,5008,5008
 dw 5066,5132,5190,5268,5337,5414,5484,5556,5616,5616,5636,5652
 dw 5688,5724,5730,5747,5751,5756,5818,5836,5885,5899,5913,5931
 dw 5947,5954,6020,6028,6035,6047,6052,6056,6079,6079,6110,6141
 dw 6173,6200,6230,6247,6266,6281,6315,6350,6380,6420,6453,6480
 dw 6513,6534,6567,6602,6636,6658,6696,6737,6770,6825,6854,6882
 dw 6918,6939,6981,7010,7044,7091,7112,7162,7181,7220,7247,7288
 dw 7318
 db 'Nedostatek pamàti.'
 db 'Nelze otev©°t soubor.'
 db 'Nelze á°st ze souboru.'
 db 'Nekorektn° parametry.'
 db 'Soubor nenalezen.'
 db 'P©°stup odep©en.'
 db 'Neplatn† cesta.'
 db 'Nelze ps†t do souboru.'
 db 'Selh†n° DPMI.'
 db 'Nedostatek konvenán° pamàti.'
 db 'Pot©ebuji DOS verze p©inejmen®°m'
 db 'Neplatny disk'
 db 'Selhalo nastaven° fantom disku'
 db 'Selhal test fantom disku'
 db 'Zabils koáku, ëivotñ màla'
 db 'Nelze vytvo©it soubor.'
 db 'Nelze zav©°t soubor.'
 db 'P©°li® velkò soubor.'
 db 'V readonly m¢du nelze zapisovat na disk.'
 db 'Sluëba Event Wait je obsazena.'
 db 'DialogovÇ okno je vàt®° neë obrazovka, zkus vy®®° rozli®en°.'
 db 'M†lo pamàti na vol†n° shellu "$".'
 db 'Ne£spà®nÇ vol†n° shellu "$".'
 db 'Selhalo naáten° souboru.'
 db 'Selhalo uloëen° souboru.'
 db 'Selhalo vol†n° shellu.'
 db 'Adresa'
 db 'Nejde nastavit zobrazovac° m¢d.'
 db 'Vadnò VESA BIOS. Po©iÉ si slu®nàj®° nebo pouëij VGA rozli®en°.'
 db 'Screen=nil. Je pot©eba nejprve nastavit nàjakò m¢d.'
 db 'Bitmapy maj° rñznÇ modely. Je pot©eba je p©evÇst na spoleánò.'
 db 'Vadnò font.'
 db 'Pokus o nastaven°/konverzi fontu pro tyto £áely p©°li® velkÇho.'
 db 'Chyba v INI souboru na ©†dce:'
 db 'ChybnÇ hexadecim†ln° á°slo v INI souboru na ©†dce:'
 db 'Intern° chyba INI readeru.'
 db 'Ä°slo mimo rozsah $..$ v INI souboru na ©†dce:'
 db 'Promànn† m† bòt á°slo v INI souboru na ©†dce:'
 db 'ReadOnly m¢d, vynech†v†m pr†ci s'
 db 'Alokuje® moc blokñ konvenán° pamàti. Pro autora: zvy® si maxDosBlocks.'
 db 'blokñ konvenán° pamàti neuvolnàno.'
 db 'Tvoje grafick† karta se zbl†znila. Volej doktora d.ment@email.cz!'
 db 'Nenahazuje se ret, intern° chyba.'
 db 'Fuj bios, sluëba load user font zmànila doublescanning.'
 db 'minulò m¢d neuvolnil timer'
 db 'ë†dn† bitmapa na vstupu.'
 db 'p©°li® velk† li®ta.'
 db '- TEST GRAFICKê KARTY -'
 db 'ûiÉ se instrukcemi na obrazovce.'
 db 'Pokud jsi v oknà, p©epni do fullscreenu!'
 db '...ENTER - pokraáov†n°...'
 db 'Jestli se text hòbe, stiskni ENTER.'
 db 'V opaánÇm p©°padà ESC.'
 db 'ENTER jestli se text cuk†, jinak ESC'
 db 'Stiskni ENTER.'
 db 'Stiskni ESC.'
 db 'Je-li vidàt jen pñlkruënice, stiskni ESC.'
 db 'Stiskni ENTER, je-li cel†.'
 db 'Stiskni MEZERNãK, je-li cel†.'
 db 'Je-li sloupec textu uprost©ed obrazovky, stiskni ENTER. Je-li vychòlen doprava nebo doleva, stiskni ESC.'
 db 'Pokud se kurzor pohybuje kolmo (v jednom sloupci), stiskni ENTER. Jinak ESC.'
 db 'Pokud se text pohybuje plynule, stiskni ENTER. Jinak ESC.'
 db 'Pokud se text'
 db 'pohybuje plynule,'
 db 'stiskni ENTER.'
 db 'Jinak ESC.'
 db 'Postr†d†m soubor'
 db 'Soubor $ jië existuje.'
 db 'Adres†© $ neexistuje.'
 db 'Nelze otev©°t soubor'
 db 'Nelze á°st ze souboru'
 db 'Nelze naá°st celò soubor'
 db 'Nelze vytvo©it soubor'
 db 'Nelze ps†t do souboru'
 db 'asi je m†lo m°sta na disku.'
 db 'Nelze zav©°t soubor'
 db 'Nelze p©ejmenovat soubor'
 db 'Nelze smazat soubor'
 db 'na'
 db 'Nelze zjistit velikost souboru'
 db 'Nelze zjistit atributy souboru'
 db 'Nelze nastavit atributy souboru'
 db 'Nelze vytvo©it adres†©'
 db 'Nelze vstoupit do adres†©e'
 db 'Nelze smazat adres†©'
 db 'Bàhem akce nastala chyba.'
 db 'Pokraáuj;Pok.vëdy;Skonái;Sko.vëdy'
 db 'õpatn† á°seln† soustava'
 db 'õpatn† cifra na vstupu.'
 db 'Chyba p©°stupu ke streamu'
 db 'Nelze inicializovat stream'
 db 'Äten° za koncem streamu'
 db 'Nelze ps†t do streamu'
 db 'Get neregistrovanÇho typu'
 db 'Put neregistrovanÇho typu'
 db 'MÇdium chr†nàno proti z†pisu.'
 db 'Disk'
 db 'Disky'
 db 'NEPûIPRAVEN'
 db 'Zas nic.'
 db 'PûECPèNO!'
 db 'PûãLIõ MNOHO'
 db 'SOUBOR¶!'
 db 'Äekejte,'
 db 'pros°m'
 db 'ûad°m..'
 db 'Zadej masku.'
 db 'ADRESèû'
 db 'Dàlen° nulou.'
 db 'P©ekroáen° mez° pole nebo typu.'
 db 'P©eteáen° stacku.'
 db 'Nedostatek pamàti.'
 db 'Invalid pointer operation.'
 db 'Floating point overflow.'
 db 'Floating point underflow.'
 db 'Invalid floating point operation.'
 db 'Overlay manager not installed.'
 db 'Overlay file read error.'
 db 'Pouëit° neinicializovanÇho objektu.'
 db 'Vol†n° abstraktn° metody.'
 db 'Stream registration error.'
 db 'Indexov†n° v kolekci mimo rozsah.'
 db 'P©eteáen° kolekce.'
 db 'AritmetickÇ p©eteáen°.'
 db 'General Protection Fault, hehe :).'
 db 'Break, taky ©e®en°.'
 db 'Pouziti: FN [options] [zdroj [cil]]'
 db '  -i jen vypise informace o fontech zdroj'
 db '  -f jen vypise informace o formatech'
 db '  -p prevede font na proporcionalni'
 db '  -ncislo prevede font na neproporcionalni, cislo je sirka, zadne cislo=detekce'
 db '  -r umozni prejmenovat font (nazev v headeru, ne nazev souboru)'
 db '  -first-last rika, ze font obsahuje pouze znaky first az last (napr. -32-255)'
 db '  -wcislo udava sirku znaku ve FNT v pixelech, implicitne 8'
 db '  -scislo posune vsechny znaky nahoru (tak lze vytvorit superscript)'
 db '  -k prevede font z CentralEurope na Kameniky (chces jinou konverzi? call me)'
 db '  -v zpracuje vsechny fonty obsazene v souboru'
 db '  -cslovo nejake slovo obsazene v .FON v headeru kazdeho fontu, implicitne (c)'
 db '   (neznam format .FON, fonty vyhledavam podle tohoto slova)'
 db '  :lang volba jazyka (:cz nebo :eng)'
 db '  Pokud je zadan jen zdroj, font se nastavi na obrazovce.'
 db '  Pokud je zadan i cil, program se pokusi o konverzi.'
 db '  Zdroj i cil mohou obsahovat * a ? (napr. FN *.fnt *.fn).'
 db 'Formaty (serazene od nejjednodussiho k nejkomplexnejsimu):'
 db '  FNT - nespakovane bitmapy, sirka 8 pixelu, vyska se autodetekuje'
 db '  FNP - jako FNT ale pred kazdym znakem je byte sirka(0-8)'
 db '  RIF - magic "af"; pchar copyright; word vyska(0-24),lastchar (firstchar=32);'
 db '        tablo[word ofs_od_zacatku_bitmap,sirka(0-16)]; hromada bitmap'
 db '  FN  - magic "Îm’onÁ "; pchar name; char firstchar,lastchar; short sizeover,'
 db '        sizeunder; short addspace; byte future; tablo[short relx,rely;'
 db '        byte sir,vys,shift; word ofs_od_zacatku_souboru]; hromada bitmap'
 db '  FON - copyright, copyright, copyright, chaos, copyright...'
 db 'Nejak moc parametru.'
 db 'Nezn†mò parametr'
 db 'Chaos 1, sezen mi popis formatu FON.'
 db 'Chaos 2, sezen mi popis formatu FON.'
 db 'Fontu:'
 db 'Pouzit font cislo'
 db 'Font'
 db 'Vyska'
 db 'õ°©ka $ neodpovida parametrum - neni nasobkem $ (znaku*sirka).'
 db 'Prilis velky font.'
 db 'Interni chyba, spatna velikost vygenerovaneho fn.'
 db 'Expand failed.'
 db 'Shrink failed.'
 db 'Z†pis do form†tu .'
 db 'nen° podporov†n.'
 db 'Load $.'
 db 'Rename (zadej libovolne dlouhe jmeno fontu, uklada se do headeru):'
 db 'Proporc.'
 db 'Noprop.'
 db 'Superscript.'
 db 'Show.'
 db 'Save'
 db 'Nezn†mò form†t souboru.'
 db 'Pro takovò form†t nem†m loader.'
 db 'Pro takovò form†t nem†m writer.'
 db 'Nepodporovanò áernob°lò obr†zek!'
 db 'Nepodporovanò typ komprese!'
 db 'Nepodporovan† barevn† hloubka!'
 db 'Postr†d†m paletu!'
 db 'Neoáek†van† paleta!'
 db 'Chyba v datech!'
 db 'P©°li® mnoho Huffmanovòch tabulek!'
 db 'P©°li® mnoho kvantizaán°ch tabulek!'
 db 'P©°li® mnoho barevnòch sloëek!'
 db 'Neprokl†danÇ obr†zky nejsou podporov†ny!'
 db 'Nespr†vnò poáet barevnòch sloëek!'
 db 'Chybn† velikost znaáky DRI!'
 db 'Chybn† velikost hlaviáky souboru!'
 db 'DHL nen° podporov†no!'
 db 'Nalezena nezn†m† znaáka v datech!'
 db 'Barevnò model CMYK nen° podporov†n!'
 db 'Barevnò model YIQ nen° podporov†n!'
 db 'Nezn†mò barevnò model!'
 db 'Aritmetick† komprese nen° podporov†na!'
 db 'Soubory typu HSI JPEG nejsou podporov†ny!'
 db 'Neoáek†van† znaáka konce souboru!'
 db 'Nebyla definov†na ë†dn† Huffmanova dekompresn° tabulka!'
 db 'Nepodporovanò typ prokl†d†n°!'
 db 'Neoáek†van† znaáka v datech!'
 db 'Prokl†d†n° obr†zkñ nen° podporov†no!'
 db 'P©°li® velkò obr†zek!'
 db 'Podporov†ny jsou pouze 256barevnÇ obr†zky!'
 db 'Chyba CRC v hlaviáce souboru!'
 db 'Nalezen neoáek†vanò konec souboru!'
 db 'Obr†zky v progresivn°m m¢du nejsou podporov†ny!'
 db 'Nezn†mò typ komprese!'
 db 'Dekompresn° buffer vàt®° neë 32KB nen° podporov†n!'
 db 'Nezn†mò typ filtru!'
 db 'Chybn† velikost nekomprimovanÇho bloku!'
 db 'Alfa kan†l nen° podporov†n!'
 db 'P©°li® velk† animace pro indirect player.'
 db 'Pamàü staá° jen na $% obr†zku.'
end;

{$endif}
